#
# for spring
#
server:
  port: 8080
  servlet:
    context-path: /

#
# for spring
#
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # for db
  datasource:
    url: jdbc:mysql://localhost:3306/db_sb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  # for freemarker
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
    # for jpa
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true

#
# for mybatis
#
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.wxm.demo.**.entity
  mapper-locations: mybatis/**/*Mapper.xml

#
# for log
#
logging:
  level:
    com.wxm.demo: DEBUG
    org.springfromework.web: info